# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_auto_20160609_1958'),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='companies',
            field=models.ManyToManyField(blank=True, to='custom_auth.Company'),
        ),
    ]
