# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
